# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    container_name: postgres-database
    image: postgres:15.1
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=user
      - POSTGRES_DB=postgres

  pgAdmin:
    container_name: pgAdmin-client
    depends_on:
      - db
    image: dpage/pgadmin4:6.17
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=superman@google.com 
volumes:
  postgres-db: